# Generated by Django 5.0.6 on 2024-05-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_precio_venta_total_remove_servicio_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
    ]
