# Generated by Django 5.0.6 on 2024-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='precio',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='total',
        ),
    ]
