# Generated by Django 5.0.6 on 2024-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_cantidad_remove_venta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(max_length=255),
        ),
    ]
